// src/App.svelte
<header>
	<div class="item logo">
		<img src="/assets/img/logo.svg" alt="logo" />
		<span>YouTubeTweak</span>
	</div>
	{#each ["player", "comment", "other", "about"] as key}
		<button
			class="item {tab === key ? 'active' : ''}"
			onclick={() => {
				tab = key;
			}}
		>
			{$_(`tabs.${key}.title`)}
		</button>
	{/each}
</header>

<main class="youtube-tweak-app">
	{#if tab === "player"}
		<div class="card">
			<div class="card-title">倍速按钮</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.enableSpeedButtons"]} />
					<span>显示倍速按钮</span>
				</label>
				<p>启用的按钮：</p>
				<div class="form-item-group">
					{#each [0.25, 0.5, 1, 1.25, 1.5, 2, 3] as speed}
						<label class="form-item">
							<input type="checkbox" bind:group={settings["player.ui.speedButtons"]} value={speed} />
							<span>{speed}x</span>
						</label>
					{/each}
				</div>
			</div>
		</div>
		<div class="card">
			<div class="card-title">按钮隐藏</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.autoplay"]} />
					<span>隐藏自动播放按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.subtitles"]} />
					<span>隐藏字幕按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.settings"]} />
					<span>隐藏设置按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.miniPlayer"]} />
					<span>隐藏迷你播放器按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.pip"]} />
					<span>隐藏画中画按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.size"]} />
					<span>隐藏宽画幅(剧场模式)按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.remote"]} />
					<span>隐藏远程播放(在电视上播放)按钮</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideButton.fullscreen"]} />
					<span>隐藏全屏按钮</span>
				</label>
			</div>
		</div>
		<div class="card">
			<div class="card-title">界面</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.ui.hideCeElement"]} />
					<span>半透明结尾的推荐视频/作者</span>
				</label>
			</div>
		</div>
		<div class="card">
			<div class="card-title">其他</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["player.settings.maxVolume"]} />
					<span>最大音量时关闭音量均衡(真正100%音量)</span>
				</label>
			</div>
		</div>
	{:else if tab === "comment"}
		<div class="card">
			<div class="card-title">昵称</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["comment.nickname"]} />
					<span>显示评论者昵称(频道名称)</span>
				</label>
			</div>
		</div>
		<div class="card">
			<div class="card-title">评论</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["comment.autoShowMore"]} />
					<span>自动展开长评论</span>
				</label>
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["comment.autoTranslate"]} />
					<span>自动翻译评论</span>
				</label>
			</div>
		</div>
	{:else if tab === "other"}
		<div class="card">
			<div class="card-title">首页</div>
			<div class="card-body">
				<label class="form-item">
					<input type="checkbox" bind:checked={settings["index.videoPerRow.enable"]} />
					<span> 固定首页推荐视频每行数量 </span>
					<input
						type="number"
						style="width: 50px; margin-left: 5px"
						bind:value={settings["index.videoPerRow.count"]}
						min="1"
						max="10"
						onblur={() => {
							if (
								!/^\d+$/.test(settings["index.videoPerRow.count"].toString()) ||
								settings["index.videoPerRow.count"] < 1 ||
								settings["index.videoPerRow.count"] > 10
							) {
								settings["index.videoPerRow.count"] = 4;
							}
						}}
					/>
				</label>
			</div>
		</div>
	{:else if tab === "about"}
		<div class="about">
			<img src="assets/img/logo.svg" alt="logo" />
			<p class="title">YouTube Tweak</p>
			<p class="version">v1.0.0<br /><span>Build at 2025-05-13 00:00:00</span></p>
			<p class="config">
				<button class="btn">导出设置 ⤴️</button>
				<button class="btn">导入设置 ⤵️</button>
				<button class="btn" onclick={resetSetting}>重置设置 🔄</button>
			</p>
			<p>Copyright &copy; 2025 <a href="https://dark495.me/" target="_blank">Dark495</a></p>
			<p class="link">
				<a href="https://github.com/xlch88/YouTubeTweak" target="_blank">⭐Github</a> |
				<a href="https://github.com/xlch88/YouTubeTweak/releases" target="_blank">📓Changelog</a> |
				<a href="https://github.com/xlch88/YouTubeTweak/issues" target="_blank">❓Issues</a>
			</p>
		</div>
	{/if}
</main>

<script>
import { onMount, tick } from "svelte";
import config, { DEFAULT_CONFIG } from "./util/config.js";
import { _ } from "svelte-i18n";
import { waitLocale } from "svelte-i18n";

export async function preload() {
	// awaits for the loading of the 'en-US' and 'en' dictionaries
	return waitLocale();
}

let tab = $state("about");

let settings = $state({ ...DEFAULT_CONFIG });
let isSettingsInit = false;
config.init().then((v) => {
	Object.assign(settings, {
		...v,
	});

	tick().then(() => {
		isSettingsInit = true;
	});
});

$effect(() => {
	Object.values(settings); // wtf 这太tm可怕了 我watch呢??? 老子要回去写vue😭😭😭😭
	if (!isSettingsInit) return;
	config.set(null, $state.snapshot(settings));
});

onMount(() => {});

function resetSetting() {
	if (confirm("确定要重置设置吗？")) {
		Object.assign(settings, {
			...DEFAULT_CONFIG,
		});
		tab = "player";
	}
}
</script>

<style lang="scss">
main {
	margin-top: 40px;
	height: 450px;
	overflow-y: auto;
	//background: #000;
	//width: 100px;
	//height: 100px;
}
header {
	position: fixed;
	height: 40px;
	width: 100%;
	top: 0;
	display: flex;
	flex-direction: row;
	flex-wrap: nowrap;
	justify-content: space-between;
	align-items: center;
	box-shadow: 0 0 10px rgba(#000, 0.3);
	background: #fff;

	.item {
		appearance: none;
		padding: 5px;
		height: 100%;
		flex: 1;
		line-height: 30px;
		text-align: center;
		border: none;
		background: none;
		cursor: pointer;

		&.active {
			background: rgba(#000, 0.05);
		}
		&:hover {
			background: rgba(#000, 0.1);
		}

		&.logo {
			display: flex;
			align-items: center;
			padding: 0 10px;
			background: #fff;
			cursor: default;

			img {
				width: 30px;
				height: 30px;
				margin-right: 5px;
			}
			span {
				font-weight: bolder;
				font-size: 15px;
				line-height: 14px;
				font-family: "Trebuchet MS";
			}
		}
	}
}
.card {
	background: #fff;
	margin: 10px;
	border-radius: 5px;
	padding: 10px;
	.card-title {
		font-size: 15px;
		font-weight: bolder;
		padding-bottom: 5px;
		margin-bottom: 5px;
		border-bottom: 1px solid #eee;
	}
	.card-body {
		p {
			color: #7e8299;
			margin-bottom: 0;
			margin-top: 10px;
		}
	}
}
.form-item {
	display: flex;
	align-items: center;

	&:hover input[type="checkbox"] {
		background-color: rgba(#000, 0.1);
	}

	input[type="checkbox"] {
		appearance: none;
		width: 18px;
		height: 18px;
		border: 1.5px solid #b2b2b2;
		border-radius: 4px;
		background-color: white;
		cursor: pointer;
		position: relative;
		margin-left: 0;
		transition:
			background-color 0.3s,
			border-color 0.3s;

		&:checked {
			background-color: #2196f3;
			border-color: #2196f3;

			&::after {
				content: "";
				position: absolute;
				left: 5px;
				top: 1px;
				width: 3px;
				height: 8px;
				border: solid #ffffff;
				border-width: 0 2px 2px 0;
				transform: rotate(45deg);
			}
		}
	}
}
.form-item-group {
	display: flex;
	flex-direction: row;
	flex-wrap: nowrap;
	justify-content: space-between;
}
.about {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	height: 100%;
	background: #fff;
	img {
		width: 150px;
		height: 150px;
	}
	p {
		margin: 10px 0;
		text-align: center;
		&.title {
			font-size: 20px;
			font-weight: bolder;
			margin-top: 10px;
		}
		&.version {
			font-size: 15px;
			margin-bottom: 50px;
			span {
				color: rgba(#000, 0.5);
			}
		}
	}
}
</style>

// src/entrypoints/popup/App.vue
<template>
	<template v-if="action === 'popup'">
		<header>
			<a class="item logo" target="_blank" href="https://github.com/xlch88/YouTubeTweak">
				<img src="@/assets/img/logo.svg" alt="logo" />
				<span><small>YouTube</small>Tweak</span>
			</a>
			<button
				v-for="key in ['player', 'comment', 'other', /*'insights', */ 'general']"
				:key="key"
				class="item"
				:class="{ active: tab === key }"
				@click="tab = key"
			>
				<span>{{ $t(`tabs.${key}.title`) }}</span>
			</button>
		</header>

		<main>
			<player v-if="tab === 'player'"></player>
			<comment v-else-if="tab === 'comment'"></comment>
			<other v-else-if="tab === 'other'"></other>
			<general v-else-if="tab === 'general'"></general>
			<insights v-else-if="tab === 'insights'"></insights>
		</main>
	</template>
	<installed v-else-if="action === 'installed'"></installed>
</template>

<script setup>
import useConfigStore from "./util/config.js";
import { ref, provide } from "vue";
import Other from "./pages/other.vue";
import Player from "./pages/player.vue";
import Comment from "./pages/comment.vue";
import Installed from "./pages/installed.vue";
import General from "./pages/general.vue";
import Insights from "./pages/insights.vue";

const tab = ref("player");
const action = ref("popup");

const params = new URLSearchParams(window.location.search);
if (params.get("action")) {
	action.value = params.get("action");
}

if (!(window === window.top && chrome?.extension?.getViews({ type: "popup" })?.includes(window))) {
	document.body.style.width = "initial";
	document.body.style.height = "initial";
}

provide("setTab", (v) => {
	tab.value = v;
});
</script>

<style lang="scss">
main {
	margin-top: 40px;
	height: 100%;
	width: 100%;
	overflow-y: auto;
	//background: #000;
	//width: 100px;
	//height: 100px;
}
header {
	position: fixed;
	z-index: 9999;
	height: 40px;
	width: 100%;
	top: 0;
	display: flex;
	flex-direction: row;
	flex-wrap: nowrap;
	justify-content: space-between;
	align-items: center;
	box-shadow: 0 0 10px rgba(#000, 0.3);
	background: #fff;
	padding: 0 10px;

	.item {
		appearance: none;
		padding: 5px 0;
		height: 100%;
		line-height: 30px;
		text-align: center;
		border: none;
		background: none;
		cursor: pointer;
		word-break: keep-all;
		white-space: nowrap;
		font-size: 12px;
		transition: color 0.3s;
		flex: 1;

		&:is(button) > span {
			background: transparent;
			padding: 3px 6px;
			border-radius: 500px;
		}

		&.active {
			color: #d739e3;
			> span {
				background: rgba(215, 57, 227, 0.2);
			}
		}
		&:hover {
			color: #c15fc7;
			&.active {
				color: #c320d0;
			}
		}

		&.logo {
			display: flex;
			align-items: center;
			background: #fff;
			cursor: help;
			color: #000;

			img {
				width: 30px;
				height: 30px;
				margin-right: 5px;
			}
			span {
				font-weight: bolder;
				font-size: 15px;
				line-height: 12px;
				font-family: "Trebuchet MS", serif;
				display: flex;
				flex-direction: column;
				text-align: left;

				small {
					font-size: 7px;
					line-height: 7px;
					color: rgba(0, 0, 0, 0.5);
				}
			}

			&:hover {
				color: #8f5bff;
			}
		}
	}
}
.card {
	background: #fff;
	margin: 10px;
	border-radius: 5px;
	padding: 10px;
	box-shadow:
		0 7px 14px 0 rgba(65, 69, 88, 0.1),
		0 3px 6px 0 rgba(0, 0, 0, 0.07);

	.card-title {
		font-weight: bold;
		border-bottom: 1px solid #eee;
		background: rgb(249, 250, 253);
		margin: -10px -10px 10px -10px;
		padding: 10px;
		font-size: 13px;
		border-radius: 5px 5px 0 0;
	}
	.card-body {
		p {
			color: #7e8299;
			margin-bottom: 0;
			margin-top: 10px;
		}
	}
}
.form-item {
	display: flex;
	align-items: center;

	&:hover input[type="checkbox"]:not(:checked):not(:focus):not(:disabled) {
		background-color: rgba(#000, 0.1);
	}
}
.form-item-group {
	display: flex;
	flex-direction: row;
	flex-wrap: nowrap;
	justify-content: space-between;
}
</style>
